name: flutter_stripe_web
description: A Flutter library for integrating Stripe payment processing in web applications.
version: 0.1.0
homepage: https://github.com/MuhammadUsamaProgrammer/flutter_stripe_web
repository: https://github.com/MuhammadUsamaProgrammer/flutter_stripe_web
issue_tracker: https://github.com/MuhammadUsamaProgrammer/flutter_stripe_web/issues
environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.10.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  build_web_compilers: ^3.2.0
flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterStripeWebPlugin
        fileName: flutter_stripe_web.dart
        dartPluginClass: FlutterStripeWeb
        webOnly: true